name: bucket_push
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  bucket_push:
    runs-on: ubuntu-latest
    name: Update a Textile bucket
    steps:
    - name: Bucket push action
      id: push
      uses: textileio/github-action-bucket-push@v1
      with:
        bucket-name: 'bucket-push-action'
        path: '*'
        token: ${{ secrets.TEXTILE_AUTH_TOKEN }}
    # Use the output from the `hello` step
    - name: Get the output CID
      run: echo "The CID was ${{ steps.push.outputs.cid }}"